/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "ysyx_24100027_CPU.v:1" *)
module ysyx_24100027_CPU(rst, clk);
  (* src = "ysyx_24100027_CPU.v:3" *)
  input clk;
  (* src = "ysyx_24100027_CPU.v:2" *)
  input rst;
endmodule
